# infra/ansible/roles/ci_stack/handlers/main.yml
- name: Restart CI stack
  community.docker.docker_compose_v2:
    project_src: /opt/ci
    state: present
    recreate: always

- name: Cleanup CI stack
  community.docker.docker_compose_v2:
    project_src: /opt/ci
    state: absent
    remove_orphans: true
    rmi: all                # Also removes images
    remove_volumes: true    # Optional: remove named volumes

