name: "Provision Jenkins with Ansible"

on:
  workflow_dispatch:

jobs:
  configure-jenkins:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2  # Change if needed

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/jenkins-key.pem
          chmod 600 ~/.ssh/jenkins-key.pem

      - name: Disable Ansible Host Key Checking
        run: echo "ANSIBLE_HOST_KEY_CHECKING=False" >> $GITHUB_ENV

      - name: Install Ansible and AWS Collections
        run: |
          sudo apt update
          sudo apt install -y ansible python3-boto3 python3-pip jq
          pip3 install botocore boto3
          ansible-galaxy collection install amazon.aws

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Ansible Playbook to Install Jenkins
        run: ansible-playbook infra/ansible/install-jenkins.yaml
